//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id { get; set; }
        public int idUser { get; set; }
        public int idEmployes { get; set; }
        public int idStatus { get; set; }
    
        public virtual Employes Employes { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
