//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainDeport
    {
        public int id { get; set; }
        public string Name { get; set; }
        public int idPosition { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
